appvincart/appvincart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings
# from rest_framework_simplejwt.views import (
#     TokenObtainPairView,
#     TokenRefreshView,
# )

# from django.conf import settings
# from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/',include('authapp.urls')),
    path('',include('productapp.urls')),
    path('cart/',include('cartapp.urls')),
    path('order/',include('orderapp.urls')),
    path('pay/',include('paymentapp.urls')),
    
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

appvincart/authapp/urls.py
from django.urls import path
from .views import SendPasswordResetEmailView, UserChangePasswordView, UserPasswordResetView, UserProfileView, UserRegisterationView, UserLoginView, UserLogoutView

urlpatterns=[
    path('register/', UserRegisterationView.as_view() ,name='register'),
    path('login/', UserLoginView.as_view() ,name='login'),
    path('profile/', UserProfileView.as_view() ,name='profile'),
    path('changepassword/', UserChangePasswordView.as_view() ,name='changepassword'),
    path('resetforgotpassword/',SendPasswordResetEmailView.as_view(), name='reset_forgot_password'),
    path('resetpassword/<uid>/<token>/',UserPasswordResetView.as_view(), name='reset_password'), # adding slash at the ed of writting this url is really important, although automatically adds a slash at the end ; but that's troublesome too.
    path('logout/',UserLogoutView.as_view(), name='logout'),
]

appvincart/authapp/models.py
# from datetime import datetime
from MySQLdb import IntegrityError
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

gender_choices=(
    ('M', 'Male'),
    ('F', 'Female'),
    ('O', 'Other'),
    
)

class Role(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name
#table is first created to be able to have users by :
# >>> from authapp.models import Role 
# >>> admin_role = Role.objects.create(name="admin")
# >>> regular_role = Role.objects.create(name="regular") 
# >>> roles =Role.objects.all()
# >>> print(roles)
# <QuerySet [<Role: admin>, <Role: regular>]>
# >>>

class UserManager(BaseUserManager):
    
    def create_user(self, email, first_name, last_name, phone, address, gender, password=None, password2=None):
        if not email:
            raise ValueError("User must have a valid email address ")
        # self.model means the class this manager is attached to
        user = self.model(
            email = self.normalize_email(email),
            first_name = first_name,
            last_name = last_name,
            phone = phone,
            address = address,
            gender = gender
        )
        user.set_password(password) # it will hash our password to save it
        user.save(using=self._db)
        return user
    
    def create_superuser(self, email, first_name,last_name, phone, address, gender, password=None):
        
        user=self.create_user(
            email = email,
            first_name =first_name,
            last_name = last_name,
            phone = phone,
            address = address,
            gender = gender,
            password = password
        )
        user.role_id = Role.objects.get(name='admin')
        user.save(using=self._db)
        return user
    
# absractuser can be used too where password will be automatically handled by AbstractUser
class User(AbstractBaseUser):

    first_name = models.CharField(max_length=50, null=False)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100, null=False, unique=True)
    phone = models.CharField(max_length= 15)
    address = models.CharField(max_length=200)
    gender = models.CharField(max_length=1, choices=gender_choices)
    registered_at = models.DateTimeField(auto_now_add = True)
    # updated_at = models.DateTimeField(auto_now = True)
    role_id = models.ForeignKey(Role,on_delete=models.SET_NULL, blank=True, null=True)
    
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name', 'phone', 'address', 'gender'] #['First_Name','Password']
    
    objects = UserManager()
    
    def __str__(self):
        return self.email
    
    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True
    
    def has_module_perms(self, app_label):
        "Does user have permissions to view the app 'app_label'?"
        return True
    
    @property
    def is_active(self):
        # it was by default true that's why
        return True
    
    @property
    def is_admin(self):
        return self.role_id.name == 'admin' if self.role_id else False
    
    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin
    
    

appvincart/authapp/views.py
from base64 import urlsafe_b64encode
from tokenize import TokenError
from django.shortcuts import redirect
from rest_framework.response import Response
from rest_framework import status
from rest_framework.views import APIView

from .models import User
from .serializers import SendPasswordResetEmailSerializer, UserLoginSerializer, UserPasswordResetSerializer, UserProfileSerializer, UserRegistrationSerializer, UserChangePasswordSerializer #,LogOutSerializer
from django.contrib.auth  import authenticate
from .renderers import UserRenderer, SuccessRenderer
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework_simplejwt.tokens import RefreshToken  #for refresh token
from rest_framework.permissions import IsAuthenticated
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.utils.encoding import force_bytes
from .utils import EmailUtils


# generating token manually - jwt token # HS256 the algo used in jwt token by default
def get_tokens_for_user(user):
    refresh = RefreshToken.for_user(user)

    return {
        'refresh': str(refresh),
        'access': str(refresh.access_token),
    }

class UserRegisterationView(APIView):
    
    renderer_classes =[UserRenderer, SuccessRenderer, TemplateHTMLRenderer]
    template_name = 'registration.html'
    
    def get(self, request, format=None):
        reg_form = UserRegistrationSerializer()
        return Response({'reg_form': reg_form}, template_name=self.template_name)
    # we use post as user will give data to register himself , from here the request's data will be send to serializer
    def post(self, request, format = None):
        serializer = UserRegistrationSerializer(data = request.data)
        if serializer.is_valid(raise_exception = True):
            user = serializer.save()
            token = get_tokens_for_user(user)
            # return Response({'token':token ,'msg':'Registration Successful'}, status = status.HTTP_201_CREATED) # status is 201 as data is being created
            return redirect('login')
        return Response(serializer.errors, status = status.HTTP_400_BAD_REQUEST)

#authentication is done here
class UserLoginView(APIView):
    
    renderer_classes =[UserRenderer, SuccessRenderer, TemplateHTMLRenderer]
    template_name = 'login.html'
    
    def get(self, request, format=None):
        login_form = UserLoginSerializer()
        return Response({'login_form': login_form}, template_name=self.template_name)
    def post(self, request, format=None):
        serializer = UserLoginSerializer(data=request.data)
        #for redirection to page with this url 
        if serializer.is_valid(raise_exception = True):
            email = serializer.data.get('email')
            password = serializer.data.get('password')
            # using these it will authenticate and check if there any user with it or not
            user=authenticate(email=email, password=password) 
            if user is not None:
                token = get_tokens_for_user(user)
                #return Response({'token':token ,'msg':'Login Success'}, status = status.HTTP_201_CREATED)  # can be use to test if token is generated and what was the token
                return redirect('home')
            else:
                return Response({'errors':{'non_field_errors': ['Email or Password is not valid']}}, status = status.HTTP_404_NOT_FOUND)
            

class UserProfileView(APIView):
    renderer_classes = [UserRenderer, SuccessRenderer, TemplateHTMLRenderer]
    # it is to tell that only authenticated users are allowded the profile view means , one needed to be a user, is authenticated was necessary otherwise it was throwing long Attribute-error rather than a error message that we are getting now.
    permission_classes = [IsAuthenticated] 
    
    def get(self,request, format=None):
        # current user is send in request # we are getting this user via isauthenticated
        serializer = UserProfileSerializer(request.user) 
        return Response({"profile":serializer.data}, status = status.HTTP_200_OK, template_name='profile.html')



#change_password requires token as it is done only after login and for login authentication is need to be done
class UserChangePasswordView(APIView):
    
    renderer_classes = [UserRenderer, SuccessRenderer, TemplateHTMLRenderer]
    permission_classes = [IsAuthenticated] # to be authenticated and authorized , the token need with the request data
    template_name = 'changepassword.html'
    
    def get(self, request, format=None):
        change_password_form = UserChangePasswordSerializer()
        return Response({'login_form': change_password_form}, template_name=self.template_name)
    
    def post(self, request, format =None):
        serializer = UserChangePasswordSerializer(data=request.data, context = {'user':request.user})
        if serializer.is_valid(raise_exception =True):
            return Response({'msg':'Password Changed Successfully'}, status = status.HTTP_201_CREATED)
        return Response(serializer.errors, status = status.HTTP_400_BAD_REQUEST)
    
# for forget password
class SendPasswordResetEmailView(APIView):
    
    renderer_classes = [UserRenderer, SuccessRenderer]
    
    def post(self, request, format=None):
        serializer = SendPasswordResetEmailSerializer(data=request.data)
        if serializer.is_valid(raise_exception=True):
            email = serializer.validated_data['email']
            user = User.objects.get(email=email)
            uid = urlsafe_b64encode(force_bytes(user.id))
            token = PasswordResetTokenGenerator().make_token(user)
            link = f'http://localhost:3000/api/user/reset/{uid}/{token}'
            # Send email to user
            subject = 'Reset your password'
            message = f'Click the following link to reset your password: {link}'
            to_email = email
            EmailUtils.send_email(subject, message, to_email)
            return Response({'msg': 'Password reset link is sent. Please check your email'}, status=status.HTTP_200_OK)
            # return redirect('reset_password')   # -->  this redirect can be used in place of response in website
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


#for updating the password passed by user after resetting forget password
class UserPasswordResetView(APIView):
    
    renderer_classes = [UserRenderer, SuccessRenderer]
    
    def post(self, request, uid, token, format=None):
        serializer = UserPasswordResetSerializer(data = request.data, context={'uid':uid,'token':token })
        if serializer.is_valid(raise_exception =True):
            return Response({'msg':'Password is successfully reset'}, status = status.HTTP_200_OK)
        return Response(serializer.errors, status = status.HTTP_400_BAD_REQUEST)

class UserLogoutView(APIView):

    permission_classes = [IsAuthenticated]
    
    def post(self, request, format=None):
        try:
            refresh_token = request.data.get("refresh")
            if refresh_token:
                token = RefreshToken(refresh_token)
                token.blacklist()
                return Response({"success": "User logged out successfully."}, status=status.HTTP_200_OK)
            else:
                return Response({"error": "Refresh token not provided."}, status=status.HTTP_400_BAD_REQUEST)
        except Exception as e:
            return Response({"error": str(e)}, status=status.HTTP_400_BAD_REQUEST)

appvincart/authapp/templates/changepassword.html
{% comment %} <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Change Password</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
        }

        .container {
            max-width: 400px;
            margin: 50px auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

        h2 {
            text-align: center;
        }

        label {
            font-weight: bold;
        }

        input[type="password"] {
            width: 100%;
            padding: 10px;
            margin: 8px 0;
            box-sizing: border-box;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        button[type="submit"] {
            width: 100%;
            background-color: #4CAF50;
            color: white;
            padding: 14px 20px;
            margin: 8px 0;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

        button[type="submit"]:hover {
            background-color: #45a049;
        }
    </style>
</head>
<body>
    <div class="container">
        <h2>Change Password</h2>
        <form method="post">
            {% csrf_token %}
            <label for="id_password">New Password:</label><br>
            <input type="password" id="id_password" name="password" placeholder="Enter your new password"><br>
            
            <label for="id_password2">Confirm Password:</label><br>
            <input type="password" id="id_password2" name="password2" placeholder="Confirm your new password"><br>
            
            <button type="submit">Change Password</button>
        </form>
        <div class="form-footer">
            <p> <a href="{% url 'login'  %}">Login</a> again </p>
        </div>
    </div>
</body>
</html> {% endcomment %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Change Password</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
        }

        .container {
            max-width: 400px;
            margin: 50px auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

        h2 {
            text-align: center;
            margin-bottom: 20px;
        }

        label {
            font-weight: bold;
        }

        input[type="password"] {
            width: 100%;
            padding: 10px;
            margin: 8px 0;
            box-sizing: border-box;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        button[type="submit"] {
            width: 100%;
            background-color: #4CAF50;
            color: white;
            padding: 14px 20px;
            margin: 8px 0;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

        button[type="submit"]:hover {
            background-color: #45a049;
        }

        .success-message {
            background-color: #d4edda;
            border-color: #c3e6cb;
            color: #155724;
            padding: 15px;
            margin-bottom: 20px;
            border-radius: 4px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h2>Change Password</h2>
        {% if msg %}
        <div class="success-message">{{ msg }}</div>
        {% endif %}
        <form method="post">
            {% csrf_token %}
            <label for="id_password">New Password:</label><br>
            <input type="password" id="id_password" name="password" placeholder="Enter your new password"><br>
            
            <label for="id_password2">Confirm Password:</label><br>
            <input type="password" id="id_password2" name="password2" placeholder="Confirm your new password"><br>
            
            <button type="submit">Change Password</button>
        </form>
        <div class="form-footer">
            <p> <a href="{% url 'login'  %}">Login</a> again </p>
        </div>
    </div>
</body>
</html>

appvincart/authapp/templates/login.html
{% comment %}
-- take input for login and on correct login id and password redirect to home page from home app
-- if email or password is incorrect give warning, if the email is new ask for neew registration
-- if person click on forget password , 
then after taken entry for access to change the password, 
redirect to reset password page and then at the end again at the login page.
{% endcomment %}

{% comment %} <h2>
    <form action="" method="post">
        {% csrf_token %}

        {{login_form.as_p}}
        <input type="submit" value="Login">

    </form>
</h2> {% endcomment %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Login</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
            margin: 0;
            padding: 0;
        }

        #loginForm {
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            max-width: 500px;
            margin: auto;
            padding: 30px;
            box-sizing: border-box;
            margin-top: 50px;
        }

        h1 {
            text-align: center;
            margin-bottom: 30px;
        }

        label {
            display: block;
            font-weight: bold;
            margin-bottom: 10px;
        }

        input[type="email"],
        input[type="password"] {
            width: calc(100% - 20px);
            padding: 10px;
            margin-bottom: 20px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }

        button {
            width: 100%;
            padding: 10px;
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

        button:hover {
            background-color: #0056b3;
        }

        .form-footer {
            text-align: center;
            margin-top: 20px;
        }

        .form-footer a {
            color: #007bff;
            text-decoration: none;
        }

        .form-footer a:hover {
            text-decoration: underline;
        }
    </style>
</head>
<body>
    <form id="loginForm" method="post">
        {% csrf_token %}
        
        <h1>User Login</h1>
        
        <label for="email">Email:</label>
        <input type="email" id="email" name="email" placeholder="Enter your email" required>
        
        <label for="password">Password:</label>
        <input type="password" id="password" name="password" placeholder="Enter your password" required>
        
        <button type="submit">Login</button>

        <div class="form-footer">
            <p>Don't have an account? <a href="{% url 'register'  %}">Register</a></p>
            <p>Forgot your password? <a href="{% url 'reset_forgot_password'  %}">Forgot Password</a></p>
            <p>Back to <a href="{% url 'home'  %}">Home</a></p>
        </div>
    </form>
    <script>
        function handleLogin() {
            var formData = new FormData(document.getElementById("loginForm"));
            fetch("/auth/login/", {
                method: "POST",
                body: formData
            })
            .then(response => {
                if (!response.ok) {
                    throw new Error("Network response was not ok");
                }
                return response.json();
            })
            .then(data => {
                if (data.token) {
                    // Redirect user to home page upon successful login
                    window.location.href = "{% url 'home'  %}";
                } else if (data.errors && data.errors.non_field_errors) {
                    // Display error message for unsuccessful login
                    document.getElementById("loginError").innerText = data.errors.non_field_errors[0];
                } else {
                    console.error("Unexpected response from server");
                }
            })
            .catch(error => {
                console.error("Error:", error);
            });
            return false; // Prevent default form submission
        }
    </script>
    
    
    
</body>
</html>

appvincart/authapp/templates/profile.html
<!-- profile.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Profile</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }
        .profile-container {
            max-width: 800px;
            margin: 50px auto;
            padding: 20px;
            background-color: #f9f9f9;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        .profile-info {
            margin-top: 20px;
        }
        .profile-info p {
            margin-bottom: 10px;
        }
        .profile-info strong {
            font-weight: bold;
            margin-right: 5px;
        }
    </style>
</head>
<body>
    <div class="profile-container">
        <h1>User Profile</h1>
        <div class="profile-info">
            <p><strong>Email:</strong> {{ user.email }}</p>
            <p><strong>First Name:</strong> {{ user.first_name }}</p>
            <p><strong>Last Name:</strong> {{ user.last_name }}</p>
            <p><strong>Phone:</strong> {{ user.phone }}</p>
            <p><strong>Address:</strong> {{ user.address }}</p>
            <p><strong>Gender:</strong> {{ user.get_gender_display }}</p>
            <p><strong>Registered At:</strong> {{ user.registered_at }}</p>
        </div>
        <hr>
        <div class="form-footer">
            <p>Want to <a href="{% url 'changepassword'  %}"> Change Password </a>?</p>
            <p>Back to <a href="{% url 'home'  %}">Home</a></p>
        </div>
    </div>
    
</body>
</html>

appvincart/authapp/templates/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Registration</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
            margin: 0;
            padding: 0;
        }

        #registrationForm {
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            max-width: 500px;
            margin: 30px auto;
            padding: 30px;
            box-sizing: border-box;
        }

        h1 {
            text-align: center;
            margin-bottom: 30px;
        }

        label {
            display: block;
            font-weight: bold;
            margin-bottom: 10px;
        }

        input[type="text"],
        input[type="email"],
        input[type="password"],
        select {
            width: calc(100% - 20px);
            padding: 10px;
            margin-bottom: 20px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }

        select {
            width: 100%;
        }

        button {
            width: 100%;
            padding: 10px;
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

        button:hover {
            background-color: #0056b3;
        }

        .form-footer {
            text-align: center;
            margin-top: 20px;
        }

        .form-footer a {
            color: #007bff;
            text-decoration: none;
        }

        .form-footer a:hover {
            text-decoration: underline;
        }

        /* Modal styles */
        .modal {
            display: none; /* Hidden by default */
            position: fixed; /* Stay in place */
            z-index: 1; /* Sit on top */
            left: 0;
            top: 0;
            width: 100%; /* Full width */
            height: 100%; /* Full height */
            overflow: auto; /* Enable scroll if needed */
            background-color: rgb(0,0,0); /* Fallback color */
            background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
            padding-top: 60px;
        }

        .modal-content {
            background-color: #fefefe;
            margin: 5% auto; /* 15% from the top and centered */
            padding: 20px;
            border: 1px solid #888;
            width: 80%; /* Could be more or less, depending on screen size */
        }

        /* Close button */
        .close {
            color: #aaa;
            float: right;
            font-size: 28px;
            font-weight: bold;
        }

        .close:hover,
        .close:focus {
            color: black;
            text-decoration: none;
            cursor: pointer;
        }
    </style>
</head>
<body>
    <form id="registrationForm" method="post">
        {% csrf_token %}
        
        <h1>User Registration</h1>
        
        <label for="first_name">First Name:</label>
        <input type="text" id="first_name" name="first_name" value="{{ reg_form.first_name.value }}" required>
        
        <label for="last_name">Last Name:</label>
        <input type="text" id="last_name" name="last_name" value="{{ reg_form.last_name.value }}" required>
        
        <label for="email">Email:</label>
        <input type="email" id="email" name="email" value="{{ reg_form.email.value }}" required>
        
        <label for="phone">Phone:</label>
        <input type="text" id="phone" name="phone" value="{{ reg_form.phone.value }}" required>
        
        <label for="address">Address:</label>
        <input type="text" id="address" name="address" value="{{ reg_form.address.value }}" required>
        
        <label for="gender">Gender:</label>
        <select id="gender" name="gender" required class="form-control form-control-sm">
            <option value="M" {% if reg_form.gender.value == 'M' %} selected {% endif %}>Male</option>
            <option value="F" {% if reg_form.gender.value == 'F' %} selected {% endif %}>Female</option>
            <option value="O" {% if reg_form.gender.value == 'O' %} selected {% endif %}>Other</option>
        </select>
        
        <label for="password">Password:</label>
        <input type="password" id="password" name="password" required>
        
        <label for="password2">Confirm Password:</label>
        <input type="password" id="password2" name="password2" required>
        
        <button type="submit">Register</button>

        <div class="form-footer">
            <p>Already have an account? <a href="{% url 'login'  %}">Login</a></p>
            <p>Back to <a href="{% url 'home'  %}">Home</a></p>
        </div>
    </form>

    <!-- Success message modal -->
    <div id="successModal" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <p>Registration successful!</p>
        </div>
    </div>

    <script>
        // JavaScript to show modal after successful registration
        // Change this function to trigger the modal based on your actual implementation
        function showSuccessModal() {
            var modal = document.getElementById("successModal");
            modal.style.display = "block";

            // Close the modal when the close button is clicked
            var closeBtn = document.getElementsByClassName("close")[0];
            closeBtn.onclick = function() {
                modal.style.display = "none";
            }
        }

        // Call the showSuccessModal function when registration is successful
        // This is just an example, you should call this function based on your actual implementation
        // For example, after receiving a success response from the server
        // showSuccessModal();
    </script>
</body>
</html>